services:
  mongodb:
    image: 'mongo:latest'
    networks:
      - main
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./server
    ports:
      - 3001:80
    networks:
      - main
    volumes:
      - ./server:/home

  client:
    build: ./client
    ports:
      - 3000:80
    networks:
      - main
    volumes:
      - ./client:/home

networks:
  main:
    name: main_network
